version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pipeline_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
      POSTGRES_DB: pipeline_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
